# Generated by Django 3.1.3 on 2022-04-22 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20220422_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_offered',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
