# Generated by Django 3.1.3 on 2022-04-22 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_feedback_date_offered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='date_offered',
            new_name='date_created',
        ),
    ]
